### ISSUE TITLE
CBHC Support

### ISSUE THREAD

**Issue by xUnleqitTV** [Xpl0itU/theme-manager#2]
Hey Xpl0itU, i would like to use the Theme Manager for my Wii U, but i don´t have Tiramisu is it posibble that you add a ColdBoot Haxchi version? or is there already a CBHC version? when yes pls give me a link :)

**Comment by Xpl0itU** [comment]
no, tiramisu is required due to brick protections, please upgrade to tiramisu

**Comment by xUnleqitTV** [comment]
ah ok, is there an other Theme Manger for the Wii U that supports cbhc? (not SDCafiine) or is this the only one?

**Comment by Xpl0itU** [comment]
You have rosalina, but it’s really bad, I recommend you switch to tiramisu asap, it’s a lot better than cbhc

**Comment by xUnleqitTV** [comment]
I've installed Tiramisu now, i have one last question what happens when i start the wii u with the sd card when i have a custom theme installed?
Crashs the Wii U? or is the new Theme installed on the Wii U anddon't need the files on the sd card?

**Comment by Xpl0itU** [comment]
You need to install the theme, afterwards it will remain installed, even with no sd card insterted or no cfw running

**Comment by xUnleqitTV** [comment]
Ok nice! thank you for creating this awesome tool :)

**Comment by Xpl0itU** [comment]
Thank you too for using it, please let me know how it goes with it or if you have any other questions

**Comment by xUnleqitTV** [comment]
I've installed now my first custom theme! it looks nice and i don't have any problems :) it feels like a new console when you have seen the normal menu since 2014 :D
